package paneles.pnlreportes;

import Controlador.ControlReportes;
import Modelo.Conexion;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.LayoutManager;
import java.awt.RenderingHints;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.util.Date;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Enumeration;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.axis.CategoryAxis;
import org.jfree.chart.axis.CategoryLabelPositions;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.data.category.CategoryDataset;

public class pnlRSalidaInve extends javax.swing.JPanel {

    ControlReportes re = new ControlReportes();
    public pnlRSalidaInve() throws SQLException {
        initComponents();
        re.RellenarComboSucursal("Sucursal", "Ciudad", cbSucursalSalidaI);
        re.RellenarComboSucursal("Sucursal", "Ciudad", cbSucursalSalidaIG);
        ajustarColumnasTabla(tblSalidaInventario);
        re.actualizarFecha(lblSalidaInventario);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlsalidai = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tblSalidaInventario = new javax.swing.JTable();
        jPanel20 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        txtFechaInicio = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtFechaFinal = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        cbSucursalSalidaI = new javax.swing.JComboBox<>();
        lblSalidaInventario = new javax.swing.JLabel();
        btnGenerarSalidaI = new metodos.MyButton();
        btnGenerarSalidaI1 = new metodos.MyButton();
        jPanel10 = new javax.swing.JPanel();
        btnMostrarSalidaInventarioG = new metodos.MyButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtFechaInicioG = new com.toedter.calendar.JDateChooser();
        jLabel10 = new javax.swing.JLabel();
        txtFechaFinalG = new com.toedter.calendar.JDateChooser();
        jLabel11 = new javax.swing.JLabel();
        cbSucursalSalidaIG = new javax.swing.JComboBox<>();
        pnlSalidaInventario = new javax.swing.JPanel();
        btnGrafico = new metodos.MyButton();

        setMinimumSize(new java.awt.Dimension(1235, 720));
        setPreferredSize(new java.awt.Dimension(1235, 720));

        pnlsalidai.setMinimumSize(new java.awt.Dimension(1230, 720));
        pnlsalidai.setPreferredSize(new java.awt.Dimension(1230, 720));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setMinimumSize(new java.awt.Dimension(1220, 651));
        jPanel5.setPreferredSize(new java.awt.Dimension(1220, 651));

        jTabbedPane2.setMinimumSize(new java.awt.Dimension(1225, 639));
        jTabbedPane2.setPreferredSize(new java.awt.Dimension(1225, 639));

        tblSalidaInventario.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        tblSalidaInventario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre del Producto", "Cantidad", "Tipo de Unidad", "Precio Unitario", "Precio Total", "Fecha de Salida"
            }
        ));
        tblSalidaInventario.setEnabled(false);
        jScrollPane6.setViewportView(tblSalidaInventario);

        jPanel20.setBackground(new java.awt.Color(99, 169, 229));

        jLabel16.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 36)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Reporte de salida de inventario");

        jLabel27.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Fecha de Emisión:");

        txtFechaInicio.setDateFormatString("y-MM-d");

        jLabel7.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel7.setText("Fecha Inicio");

        jLabel8.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel8.setText("Fecha Final");

        txtFechaFinal.setDateFormatString("y-MM-d");

        jLabel6.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel6.setText("Seleccionar Sucursal:");

        cbSucursalSalidaI.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        cbSucursalSalidaI.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mostrar todas las sucursales" }));
        cbSucursalSalidaI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSucursalSalidaIActionPerformed(evt);
            }
        });

        lblSalidaInventario.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        lblSalidaInventario.setForeground(new java.awt.Color(255, 255, 255));
        lblSalidaInventario.setText("jLabel26");

        btnGenerarSalidaI.setBackground(new java.awt.Color(19, 102, 217));
        btnGenerarSalidaI.setForeground(new java.awt.Color(255, 255, 255));
        btnGenerarSalidaI.setText("Descargar");
        btnGenerarSalidaI.setBorderColor(new java.awt.Color(19, 102, 217));
        btnGenerarSalidaI.setColor(new java.awt.Color(19, 102, 217));
        btnGenerarSalidaI.setColorClick(new java.awt.Color(19, 102, 217));
        btnGenerarSalidaI.setColorOver(new java.awt.Color(66, 139, 225));
        btnGenerarSalidaI.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 14)); // NOI18N
        btnGenerarSalidaI.setRadius(10);
        btnGenerarSalidaI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarSalidaIActionPerformed(evt);
            }
        });

        btnGenerarSalidaI1.setBackground(new java.awt.Color(19, 102, 217));
        btnGenerarSalidaI1.setForeground(new java.awt.Color(255, 255, 255));
        btnGenerarSalidaI1.setText("Mostrar Tabla");
        btnGenerarSalidaI1.setBorderColor(new java.awt.Color(19, 102, 217));
        btnGenerarSalidaI1.setColor(new java.awt.Color(19, 102, 217));
        btnGenerarSalidaI1.setColorClick(new java.awt.Color(19, 102, 217));
        btnGenerarSalidaI1.setColorOver(new java.awt.Color(66, 139, 225));
        btnGenerarSalidaI1.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 14)); // NOI18N
        btnGenerarSalidaI1.setRadius(10);
        btnGenerarSalidaI1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarSalidaI1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel20Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblSalidaInventario)
                .addGap(100, 100, 100)
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addGroup(jPanel20Layout.createSequentialGroup()
                        .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(txtFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(txtFechaFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbSucursalSalidaI, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addComponent(btnGenerarSalidaI1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnGenerarSalidaI, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(61, 61, 61))
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel27)
                        .addComponent(lblSalidaInventario))
                    .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnGenerarSalidaI, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnGenerarSalidaI1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel20Layout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel20Layout.createSequentialGroup()
                            .addComponent(jLabel8)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtFechaFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel20Layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cbSucursalSalidaI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 1182, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel20, javax.swing.GroupLayout.PREFERRED_SIZE, 1182, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Reporte Tipo Tabla", jPanel9);

        btnMostrarSalidaInventarioG.setForeground(new java.awt.Color(255, 255, 255));
        btnMostrarSalidaInventarioG.setText("Generar");
        btnMostrarSalidaInventarioG.setBorderColor(new java.awt.Color(102, 160, 255));
        btnMostrarSalidaInventarioG.setColor(new java.awt.Color(102, 160, 255));
        btnMostrarSalidaInventarioG.setColorClick(new java.awt.Color(19, 102, 217));
        btnMostrarSalidaInventarioG.setColorOver(new java.awt.Color(183, 207, 255));
        btnMostrarSalidaInventarioG.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 14)); // NOI18N
        btnMostrarSalidaInventarioG.setRadius(10);
        btnMostrarSalidaInventarioG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarSalidaInventarioGActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 14)); // NOI18N
        jLabel9.setText("Fecha Inicio");

        jLabel18.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 36)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(99, 169, 229));
        jLabel18.setText("Salida de Inventario");

        txtFechaInicioG.setDateFormatString("y-MM-d");

        jLabel10.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 14)); // NOI18N
        jLabel10.setText("Fecha Final");

        txtFechaFinalG.setDateFormatString("y-MM-d");

        jLabel11.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 14)); // NOI18N
        jLabel11.setText("Seleccionar Sucursal:");

        cbSucursalSalidaIG.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 12)); // NOI18N
        cbSucursalSalidaIG.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mostrar todas las sucursales" }));
        cbSucursalSalidaIG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSucursalSalidaIGActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlSalidaInventarioLayout = new javax.swing.GroupLayout(pnlSalidaInventario);
        pnlSalidaInventario.setLayout(pnlSalidaInventarioLayout);
        pnlSalidaInventarioLayout.setHorizontalGroup(
            pnlSalidaInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1185, Short.MAX_VALUE)
        );
        pnlSalidaInventarioLayout.setVerticalGroup(
            pnlSalidaInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
        );

        btnGrafico.setForeground(new java.awt.Color(255, 255, 255));
        btnGrafico.setText("Mostrar Gráfica");
        btnGrafico.setBorderColor(new java.awt.Color(102, 160, 255));
        btnGrafico.setColor(new java.awt.Color(102, 160, 255));
        btnGrafico.setColorClick(new java.awt.Color(19, 102, 217));
        btnGrafico.setColorOver(new java.awt.Color(183, 207, 255));
        btnGrafico.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 14)); // NOI18N
        btnGrafico.setRadius(10);
        btnGrafico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGraficoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFechaInicioG, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFechaFinalG, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(cbSucursalSalidaIG, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnGrafico, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnMostrarSalidaInventarioG, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pnlSalidaInventario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel10Layout.createSequentialGroup()
                                    .addComponent(jLabel9)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtFechaInicioG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel10Layout.createSequentialGroup()
                                    .addComponent(jLabel10)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtFechaFinalG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbSucursalSalidaIG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnGrafico, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnMostrarSalidaInventarioG, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlSalidaInventario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane2.addTab("Grafica", jPanel10);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 657, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlsalidaiLayout = new javax.swing.GroupLayout(pnlsalidai);
        pnlsalidai.setLayout(pnlsalidaiLayout);
        pnlsalidaiLayout.setHorizontalGroup(
            pnlsalidaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlsalidaiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlsalidaiLayout.setVerticalGroup(
            pnlsalidaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlsalidaiLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 669, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlsalidai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 5, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlsalidai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cbSucursalSalidaIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSucursalSalidaIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbSucursalSalidaIActionPerformed

    public String SucursalSelected(int sucursalID) {
        String sucursal = "";

        if (sucursalID == 0) {
            sucursal = "0";
        }

        if (sucursalID == 1) {
            sucursal = "'SC01'";
        }

        if (sucursalID == 2) {
            sucursal = "'SC02'";
        }

        if (sucursalID == 3) {
            sucursal = "'SC03'";
        }

        if (sucursalID == 4) {
            sucursal = "'SC04'";
        }

        if (sucursalID == 5) {
            sucursal = "'SC05'";
        }

        if (sucursalID == 6) {
            sucursal = "'SC06'";
        }

        return sucursal;
    }
    
        public String SucursalSeleccionada(int sucursalID) {
        String sucursal = "";

        if (sucursalID == 0) {
            sucursal = "0";
        }

        if (sucursalID == 1) {
            sucursal = "SC01";
        }

        if (sucursalID == 2) {
            sucursal = "SC02";
        }

        if (sucursalID == 3) {
            sucursal = "SC03";
        }

        if (sucursalID == 4) {
            sucursal = "SC04";
        }

        if (sucursalID == 5) {
            sucursal = "SC05";
        }

        if (sucursalID == 6) {
            sucursal = "SC06";
        }

        return sucursal;
    }
    
    private void btnGenerarSalidaIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarSalidaIActionPerformed
        try {
            Conexion con = new Conexion();

            Connection conn = con.getConnect();

            JasperReport reporte = null;
            String path = "src\\Reportes\\rSalidaInventario.jasper";

            Map parametro = new HashMap();
            
            String sucursal = SucursalSelected(cbSucursalSalidaI.getSelectedIndex());

            parametro.put("Sucursal", sucursal);

            Date fechaInicio = txtFechaInicio.getDate();
            Date fechaFinal = txtFechaFinal.getDate();

            if (fechaInicio != null && fechaFinal != null) {

                SimpleDateFormat dateFormatFechaInicio = new SimpleDateFormat("yyyy-MM-dd"); // Por ejemplo, "dd/MM/yyyy" o "yyyy-MM-dd"
                SimpleDateFormat dateFormatFechaFinal = new SimpleDateFormat("yyyy-MM-dd");

                String dateStringFechaInicio = dateFormatFechaInicio.format(fechaInicio);
                String dateStringFechaFinal = dateFormatFechaFinal.format(fechaFinal);

                String formatDateStringFechaInicio = "'" + dateStringFechaInicio + "'";
                String formatDateStringFechaFinal = "'" + dateStringFechaFinal + "'";

                parametro.put("FechaInicio", formatDateStringFechaInicio);
                parametro.put("FechaFinal", formatDateStringFechaFinal);
            } else {
                JOptionPane.showMessageDialog(null, "Se deben ingresar ambas fechas", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            reporte = (JasperReport) JRLoader.loadObjectFromFile(path);

            JasperPrint jprint = JasperFillManager.fillReport(reporte, parametro, conn);

            JasperViewer view = new JasperViewer(jprint, false);

            view.setDefaultCloseOperation(view.DISPOSE_ON_CLOSE);

            view.setVisible(true);
        } catch (JRException ex) {
            Logger.getLogger(pnlRSalidaInve.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnGenerarSalidaIActionPerformed

    private void btnGenerarSalidaI1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarSalidaI1ActionPerformed
        try {

            Date fechaInicio = txtFechaInicio.getDate();
            Date fechaFinal = txtFechaFinal.getDate();

            if (fechaInicio != null && fechaFinal != null) {

                SimpleDateFormat dateFormatFechaInicio = new SimpleDateFormat("yyyy-MM-dd"); // Por ejemplo, "dd/MM/yyyy" o "yyyy-MM-dd"
                SimpleDateFormat dateFormatFechaFinal = new SimpleDateFormat("yyyy-MM-dd");

                String dateStringFechaInicio = dateFormatFechaInicio.format(fechaInicio);
                String dateStringFechaFinal = dateFormatFechaFinal.format(fechaFinal);

                String sucursal = SucursalSelected(cbSucursalSalidaI.getSelectedIndex());
                
                re.LlenarTablaSalidaInventario(tblSalidaInventario, cbSucursalSalidaI.getSelectedIndex(), dateStringFechaInicio, dateStringFechaFinal);
            } else {
                JOptionPane.showMessageDialog(null, "Se deben ingresar ambas fechas", "Error", JOptionPane.ERROR_MESSAGE);
            }

        } catch (SQLException ex) {
            Logger.getLogger(pnlRSalidaInve.class.getName()).log(Level.SEVERE, null, ex);
        }

        ajustarColumnasTabla(tblSalidaInventario);
    }//GEN-LAST:event_btnGenerarSalidaI1ActionPerformed

    private void btnMostrarSalidaInventarioGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarSalidaInventarioGActionPerformed

    }//GEN-LAST:event_btnMostrarSalidaInventarioGActionPerformed

    private void cbSucursalSalidaIGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSucursalSalidaIGActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbSucursalSalidaIGActionPerformed

    private void btnGraficoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGraficoActionPerformed
        graficoSalidaInventario();
    }//GEN-LAST:event_btnGraficoActionPerformed

    private void graficoSalidaInventario() {
        String sucursalEC = SucursalSeleccionada(cbSucursalSalidaIG.getSelectedIndex()); // Coloca aquí el número de sucursal deseado

        try {
            ControlReportes grafico = new ControlReportes();

            Date fechaInicio = txtFechaInicioG.getDate();
            Date fechaFinal = txtFechaFinalG.getDate();

            //String formatDateStringFechaInicio;
            //String formatDateStringFechaFinal;

            if (fechaInicio != null && fechaFinal != null) {

                SimpleDateFormat dateFormatFechaInicio = new SimpleDateFormat("yyyy-MM-dd"); // Por ejemplo, "dd/MM/yyyy" o "yyyy-MM-dd"
                SimpleDateFormat dateFormatFechaFinal = new SimpleDateFormat("yyyy-MM-dd");

                String dateStringFechaInicio = dateFormatFechaInicio.format(fechaInicio);
                String dateStringFechaFinal = dateFormatFechaFinal.format(fechaFinal);

                String formatDateStringFechaInicio = dateStringFechaInicio;
                String formatDateStringFechaFinal = dateStringFechaFinal;

                CategoryDataset dataset = grafico.getDatasetSalidaInventario(formatDateStringFechaInicio, formatDateStringFechaFinal, sucursalEC);
                JFreeChart chart = grafico.createChartSalidaInventario(dataset);

                CategoryPlot plot = chart.getCategoryPlot();
                CategoryAxis domainAxis = plot.getDomainAxis();
                domainAxis.setCategoryLabelPositions(CategoryLabelPositions.UP_90);

                ChartPanel chartPanel = new ChartPanel(chart);
                chartPanel.setPreferredSize(new Dimension(1160, 520));

                pnlSalidaInventario.setLayout(new BorderLayout());
                pnlSalidaInventario.add(chartPanel, BorderLayout.NORTH);
                
                btnMostrarSalidaInventarioG.addActionListener(new ActionListener() {
                    @Override
                    public void actionPerformed(ActionEvent e) {
                        try {
                            String newSucursalID = SucursalSeleccionada(cbSucursalSalidaIG.getSelectedIndex()); // Coloca aquí el nuevo número de sucursal deseado

                            CategoryDataset newDataset = grafico.getDatasetSalidaInventario(formatDateStringFechaInicio, formatDateStringFechaFinal, newSucursalID);

                            JFreeChart newChart = grafico.createChartSalidaInventario(newDataset);
                            chartPanel.setChart(newChart); // Actualiza el gráfico en el ChartPanel

                            CategoryPlot plot = newChart.getCategoryPlot();
                            CategoryAxis domainAxis = plot.getDomainAxis();
                            domainAxis.setCategoryLabelPositions(CategoryLabelPositions.UP_90);
                            domainAxis.setCategoryMargin(0.30);

                            chartPanel.repaint();
                        } catch (SQLException ex) {
                            Logger.getLogger(pnlRSalidaInve.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                });
                
            } else {
                JOptionPane.showMessageDialog(null, "Se deben ingresar ambas fechas", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
    
    
    private static void ajustarColumnasTabla(JTable tabla) {
        TableColumnModel columnModel = tabla.getColumnModel();
        int numColumnas = columnModel.getColumnCount();

        for (int col = 0; col < numColumnas; col++) {
            int anchoMaximo = 0;

            for (int fila = 0; fila < tabla.getRowCount(); fila++) {
                TableCellRenderer renderer = tabla.getCellRenderer(fila, col);
                Object valor = tabla.getValueAt(fila, col);
                Component componente = renderer.getTableCellRendererComponent(tabla, valor, false, false, fila, col);
                anchoMaximo = Math.max(componente.getPreferredSize().width, anchoMaximo);
            }

            TableColumn columna = columnModel.getColumn(col);
            columna.setPreferredWidth(anchoMaximo - 100); // Ajusta el ancho con un pequeño margen adicional
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private metodos.MyButton btnGenerarSalidaI;
    private metodos.MyButton btnGenerarSalidaI1;
    private metodos.MyButton btnGrafico;
    private metodos.MyButton btnMostrarSalidaInventarioG;
    private javax.swing.JComboBox<String> cbSucursalSalidaI;
    private javax.swing.JComboBox<String> cbSucursalSalidaIG;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JLabel lblSalidaInventario;
    private javax.swing.JPanel pnlSalidaInventario;
    public javax.swing.JPanel pnlsalidai;
    public javax.swing.JTable tblSalidaInventario;
    private com.toedter.calendar.JDateChooser txtFechaFinal;
    private com.toedter.calendar.JDateChooser txtFechaFinalG;
    private com.toedter.calendar.JDateChooser txtFechaInicio;
    private com.toedter.calendar.JDateChooser txtFechaInicioG;
    // End of variables declaration//GEN-END:variables
}
