package paneles.pnlreportes;

import Controlador.ControlReportes;
import Modelo.Conexion;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.LayoutManager;
import java.awt.RenderingHints;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.util.Date;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Enumeration;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.axis.CategoryAxis;
import org.jfree.chart.axis.CategoryLabelPositions;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.data.category.CategoryDataset;

public class pnlRDevoluProdu extends javax.swing.JPanel {

    ControlReportes re = new ControlReportes();
    public pnlRDevoluProdu() throws SQLException {
        initComponents();
        re.LlenarTablaDevolucionProductos(tblDevolucionProductos);
        autoResizeColumn(tblDevolucionProductos);
        re.actualizarFecha(lblDevolucionProductos);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnldevolu = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblDevolucionProductos = new javax.swing.JTable();
        jPanel24 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        lblDevolucionProductos = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        btnGenerarSalidaI5 = new metodos.MyButton();

        setMinimumSize(new java.awt.Dimension(1235, 720));
        setPreferredSize(new java.awt.Dimension(1235, 720));

        pnldevolu.setMinimumSize(new java.awt.Dimension(1230, 720));
        pnldevolu.setPreferredSize(new java.awt.Dimension(1230, 720));

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        tblDevolucionProductos.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        tblDevolucionProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblDevolucionProductos.setEnabled(false);
        jScrollPane5.setViewportView(tblDevolucionProductos);

        jPanel24.setBackground(new java.awt.Color(99, 169, 229));
        jPanel24.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel31.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("Fecha de Emisión:");
        jPanel24.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        lblDevolucionProductos.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        lblDevolucionProductos.setForeground(new java.awt.Color(255, 255, 255));
        lblDevolucionProductos.setText("jLabel26");
        jPanel24.add(lblDevolucionProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, -1, -1));

        jLabel13.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 36)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Reporte de devolución de productos");
        jPanel24.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 40, -1, -1));

        btnGenerarSalidaI5.setBackground(new java.awt.Color(19, 102, 217));
        btnGenerarSalidaI5.setForeground(new java.awt.Color(255, 255, 255));
        btnGenerarSalidaI5.setText("Descargar");
        btnGenerarSalidaI5.setBorderColor(new java.awt.Color(19, 102, 217));
        btnGenerarSalidaI5.setColor(new java.awt.Color(19, 102, 217));
        btnGenerarSalidaI5.setColorClick(new java.awt.Color(19, 102, 217));
        btnGenerarSalidaI5.setColorOver(new java.awt.Color(66, 139, 225));
        btnGenerarSalidaI5.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 14)); // NOI18N
        btnGenerarSalidaI5.setRadius(10);
        btnGenerarSalidaI5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarSalidaI5ActionPerformed(evt);
            }
        });
        jPanel24.add(btnGenerarSalidaI5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 50, 160, 40));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel24, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1378, Short.MAX_VALUE)
                    .addComponent(jScrollPane5))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel24, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout pnldevoluLayout = new javax.swing.GroupLayout(pnldevolu);
        pnldevolu.setLayout(pnldevoluLayout);
        pnldevoluLayout.setHorizontalGroup(
            pnldevoluLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnldevoluLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnldevoluLayout.setVerticalGroup(
            pnldevoluLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnldevoluLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnldevolu, javax.swing.GroupLayout.DEFAULT_SIZE, 1402, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnldevolu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnGenerarSalidaI5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarSalidaI5ActionPerformed
        try {
            Conexion con = new Conexion();

            Connection conn = con.getConnect();

            JasperReport reporte = null;
            String path = "src\\Reportes\\rDevolucionProductos.jasper";

            reporte = (JasperReport) JRLoader.loadObjectFromFile(path);

            JasperPrint jprint = JasperFillManager.fillReport(reporte, null, conn);

            JasperViewer view = new JasperViewer(jprint, false);

            view.setDefaultCloseOperation(view.DISPOSE_ON_CLOSE);

            view.setVisible(true);
        } catch (JRException ex) {
            Logger.getLogger(pnlRDevoluProdu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnGenerarSalidaI5ActionPerformed

    private void autoResizeColumn(JTable jTable1) {
        JTableHeader header = jTable1.getTableHeader();
        int rowCount = jTable1.getRowCount();

        final Enumeration columns = jTable1.getColumnModel().getColumns();
        while (columns.hasMoreElements()) {
            TableColumn column = (TableColumn) columns.nextElement();
            int col = header.getColumnModel().getColumnIndex(column.getIdentifier());
            int width = (int) jTable1.getTableHeader().getDefaultRenderer()
                    .getTableCellRendererComponent(jTable1, column.getIdentifier(), false, false, -1, col).getPreferredSize().getWidth();

            for (int row = 0; row < rowCount; row++) {
                int preferedWidth = (int) jTable1.getCellRenderer(row, col).getTableCellRendererComponent(jTable1,
                        jTable1.getValueAt(row, col), false, false, row, col).getPreferredSize().getWidth();
                width = Math.max(width, preferedWidth);
            }
            header.setResizingColumn(column); // this line is very important
            column.setWidth(width + jTable1.getIntercellSpacing().width);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private metodos.MyButton btnGenerarSalidaI5;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel lblDevolucionProductos;
    public javax.swing.JPanel pnldevolu;
    private javax.swing.JTable tblDevolucionProductos;
    // End of variables declaration//GEN-END:variables
}
