package paneles.pnlreportes;

import Controlador.ControlReportes;
import Modelo.Conexion;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.LayoutManager;
import java.awt.RenderingHints;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.util.Date;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Enumeration;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.axis.CategoryAxis;
import org.jfree.chart.axis.CategoryLabelPositions;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.data.category.CategoryDataset;

public class pnlRProduSinExis extends javax.swing.JPanel {

    ControlReportes re = new ControlReportes();
    public pnlRProduSinExis() throws SQLException {
        initComponents();
        re.LlenarTablaProductosSinExistencia(tblProductosSinExistencia);
        ajustarColumnasTabla(tblProductosSinExistencia);
        re.actualizarFecha(lblFechaProductoSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlprodusinexis = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        tblProductosSinExistencia = new javax.swing.JTable();
        jPanel23 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        lblFechaProductoSE = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        btnGenerarSalidaI4 = new metodos.MyButton();

        setMinimumSize(new java.awt.Dimension(1235, 720));
        setPreferredSize(new java.awt.Dimension(1235, 720));

        pnlprodusinexis.setMinimumSize(new java.awt.Dimension(1230, 720));
        pnlprodusinexis.setPreferredSize(new java.awt.Dimension(1230, 720));

        jPanel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblProductosSinExistencia.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        tblProductosSinExistencia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblProductosSinExistencia.setEnabled(false);
        jScrollPane8.setViewportView(tblProductosSinExistencia);

        jPanel16.add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 1190, 470));

        jPanel23.setBackground(new java.awt.Color(99, 169, 229));

        jLabel24.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Fecha de Emisión:");

        lblFechaProductoSE.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        lblFechaProductoSE.setForeground(new java.awt.Color(255, 255, 255));
        lblFechaProductoSE.setText("jLabel25");

        jLabel17.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 36)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Reporte de productos sin existencia");

        btnGenerarSalidaI4.setBackground(new java.awt.Color(19, 102, 217));
        btnGenerarSalidaI4.setForeground(new java.awt.Color(255, 255, 255));
        btnGenerarSalidaI4.setText("Descargar");
        btnGenerarSalidaI4.setBorderColor(new java.awt.Color(19, 102, 217));
        btnGenerarSalidaI4.setColor(new java.awt.Color(19, 102, 217));
        btnGenerarSalidaI4.setColorClick(new java.awt.Color(19, 102, 217));
        btnGenerarSalidaI4.setColorOver(new java.awt.Color(66, 139, 225));
        btnGenerarSalidaI4.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 14)); // NOI18N
        btnGenerarSalidaI4.setRadius(10);
        btnGenerarSalidaI4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarSalidaI4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel23Layout = new javax.swing.GroupLayout(jPanel23);
        jPanel23.setLayout(jPanel23Layout);
        jPanel23Layout.setHorizontalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel23Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel24)
                .addGap(12, 12, 12)
                .addComponent(lblFechaProductoSE)
                .addGap(46, 46, 46)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 147, Short.MAX_VALUE)
                .addComponent(btnGenerarSalidaI4, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );
        jPanel23Layout.setVerticalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel23Layout.createSequentialGroup()
                .addGap(0, 40, Short.MAX_VALUE)
                .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel23Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel24))
                    .addGroup(jPanel23Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(lblFechaProductoSE, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel17)))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel23Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGenerarSalidaI4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        jPanel16.add(jPanel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 1190, 120));

        javax.swing.GroupLayout pnlprodusinexisLayout = new javax.swing.GroupLayout(pnlprodusinexis);
        pnlprodusinexis.setLayout(pnlprodusinexisLayout);
        pnlprodusinexisLayout.setHorizontalGroup(
            pnlprodusinexisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlprodusinexisLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, 1210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        pnlprodusinexisLayout.setVerticalGroup(
            pnlprodusinexisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlprodusinexisLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(84, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlprodusinexis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 5, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlprodusinexis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnGenerarSalidaI4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarSalidaI4ActionPerformed
        try {
            Conexion con = new Conexion();

            Connection conn = con.getConnect();

            JasperReport reporte = null;
            String path = "src\\Reportes\\rProductosSinExistencia.jasper";

            reporte = (JasperReport) JRLoader.loadObjectFromFile(path);

            JasperPrint jprint = JasperFillManager.fillReport(reporte, null, conn);

            JasperViewer view = new JasperViewer(jprint, false);

            view.setDefaultCloseOperation(view.DISPOSE_ON_CLOSE);

            view.setVisible(true);
        } catch (JRException ex) {
            Logger.getLogger(pnlRProduSinExis.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnGenerarSalidaI4ActionPerformed

    private static void ajustarColumnasTabla(JTable tabla) {
        TableColumnModel columnModel = tabla.getColumnModel();
        int numColumnas = columnModel.getColumnCount();

        for (int col = 0; col < numColumnas; col++) {
            int anchoMaximo = 0;

            for (int fila = 0; fila < tabla.getRowCount(); fila++) {
                TableCellRenderer renderer = tabla.getCellRenderer(fila, col);
                Object valor = tabla.getValueAt(fila, col);
                Component componente = renderer.getTableCellRendererComponent(tabla, valor, false, false, fila, col);
                anchoMaximo = Math.max(componente.getPreferredSize().width, anchoMaximo);
            }

            TableColumn columna = columnModel.getColumn(col);
            columna.setPreferredWidth(anchoMaximo - 100); // Ajusta el ancho con un pequeño margen adicional
        }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private metodos.MyButton btnGenerarSalidaI4;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JLabel lblFechaProductoSE;
    public javax.swing.JPanel pnlprodusinexis;
    private javax.swing.JTable tblProductosSinExistencia;
    // End of variables declaration//GEN-END:variables
}
