/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package paneles;

import Controlador.ControlOrdenes;

/**
 *
 * @author carlo
 */
public class pnlAgregrarDevolucion extends javax.swing.JPanel {

    /**
     * Creates new form pnlAgregrarDevolucion
     */
    ControlOrdenes co =  new ControlOrdenes();
    public pnlAgregrarDevolucion() {
        initComponents();
       // co.RellenarCombo("categoria", "Nombre", cbCategoriaDevolucion);
        co.RellenarCombo("sucursal", "Ciudad", cbSucursalDevolucion);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pnlDevoluciones = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        cbProductoDevolucion = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txtMotivo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtCantidadDevolver = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtFechaDev = new com.toedter.calendar.JDateChooser();
        myButton2 = new metodos.MyButton();
        txtProductoID = new javax.swing.JTextField();
        myButton1 = new metodos.MyButton();
        txtProvID = new javax.swing.JTextField();
        jLabel46 = new javax.swing.JLabel();
        cbCategoriaDevolucion1 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        txtNombreProduc = new javax.swing.JTextField();
        cbSucursalDevolucion = new javax.swing.JComboBox<>();
        jLabel47 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        setMinimumSize(new java.awt.Dimension(532, 400));
        setPreferredSize(new java.awt.Dimension(532, 400));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlDevoluciones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 18)); // NOI18N
        jLabel1.setText("Nueva Devolución");
        pnlDevoluciones.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel45.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        jLabel45.setText("Seleccionar Producto:");
        pnlDevoluciones.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, 20));

        cbProductoDevolucion.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 12)); // NOI18N
        cbProductoDevolucion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar Producto" }));
        cbProductoDevolucion.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbProductoDevolucionItemStateChanged(evt);
            }
        });
        cbProductoDevolucion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbProductoDevolucionMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cbProductoDevolucionMousePressed(evt);
            }
        });
        cbProductoDevolucion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbProductoDevolucionActionPerformed(evt);
            }
        });
        pnlDevoluciones.add(cbProductoDevolucion, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 340, 40));

        jLabel3.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        jLabel3.setText("Motivo de Devolución:");
        pnlDevoluciones.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        txtMotivo.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        txtMotivo.setForeground(new java.awt.Color(102, 102, 102));
        txtMotivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMotivoActionPerformed(evt);
            }
        });
        pnlDevoluciones.add(txtMotivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 342, 140));

        jLabel4.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        jLabel4.setText("Cantidad a devolver:");
        pnlDevoluciones.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, -1, -1));

        txtCantidadDevolver.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        txtCantidadDevolver.setForeground(new java.awt.Color(102, 102, 102));
        txtCantidadDevolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantidadDevolverActionPerformed(evt);
            }
        });
        pnlDevoluciones.add(txtCantidadDevolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 390, 110, 40));

        jLabel5.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        jLabel5.setText("Fecha de devolución:");
        pnlDevoluciones.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, 135, -1));
        pnlDevoluciones.add(txtFechaDev, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 450, 220, 40));

        myButton2.setForeground(new java.awt.Color(255, 255, 255));
        myButton2.setText("Descartar");
        myButton2.setBorderColor(new java.awt.Color(102, 160, 255));
        myButton2.setColor(new java.awt.Color(102, 160, 255));
        myButton2.setColorClick(new java.awt.Color(19, 102, 217));
        myButton2.setColorOver(new java.awt.Color(183, 207, 255));
        myButton2.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 14)); // NOI18N
        myButton2.setRadius(10);
        myButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myButton2ActionPerformed(evt);
            }
        });
        pnlDevoluciones.add(myButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 520, 183, 40));

        txtProductoID.setEditable(false);
        pnlDevoluciones.add(txtProductoID, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 390, 120, -1));

        myButton1.setBackground(new java.awt.Color(19, 102, 217));
        myButton1.setForeground(new java.awt.Color(255, 255, 255));
        myButton1.setText("Registrar Devolución");
        myButton1.setBorderColor(new java.awt.Color(19, 102, 217));
        myButton1.setColor(new java.awt.Color(19, 102, 217));
        myButton1.setColorClick(new java.awt.Color(19, 102, 217));
        myButton1.setColorOver(new java.awt.Color(66, 139, 225));
        myButton1.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 14)); // NOI18N
        myButton1.setRadius(10);
        myButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myButton1ActionPerformed(evt);
            }
        });
        pnlDevoluciones.add(myButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 520, 195, 40));

        txtProvID.setEditable(false);
        pnlDevoluciones.add(txtProvID, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 430, 90, -1));

        jLabel46.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        jLabel46.setText("Seleccionar Categoria:");
        pnlDevoluciones.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, -260, 139, 20));

        cbCategoriaDevolucion1.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 12)); // NOI18N
        cbCategoriaDevolucion1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar Categoría" }));
        cbCategoriaDevolucion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCategoriaDevolucion1ActionPerformed(evt);
            }
        });
        pnlDevoluciones.add(cbCategoriaDevolucion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, -270, 340, 40));

        jLabel6.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        jLabel6.setText("Nombre del producto:");
        pnlDevoluciones.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        txtNombreProduc.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        txtNombreProduc.setForeground(new java.awt.Color(102, 102, 102));
        txtNombreProduc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreProducActionPerformed(evt);
            }
        });
        txtNombreProduc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNombreProducKeyReleased(evt);
            }
        });
        pnlDevoluciones.add(txtNombreProduc, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 340, 40));

        cbSucursalDevolucion.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 12)); // NOI18N
        cbSucursalDevolucion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar Sucursal" }));
        cbSucursalDevolucion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSucursalDevolucionActionPerformed(evt);
            }
        });
        pnlDevoluciones.add(cbSucursalDevolucion, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 340, 40));

        jLabel47.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        jLabel47.setText("Seleccionar Sucursal:");
        pnlDevoluciones.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, 20));

        add(pnlDevoluciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 580));
    }// </editor-fold>//GEN-END:initComponents

    private void txtMotivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMotivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMotivoActionPerformed

    private void cbProductoDevolucionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbProductoDevolucionActionPerformed
        co.BuscarProductosID(cbProductoDevolucion, txtProductoID, txtProvID);
    }//GEN-LAST:event_cbProductoDevolucionActionPerformed

    private void txtCantidadDevolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidadDevolverActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadDevolverActionPerformed

    private void myButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButton2ActionPerformed
       
    }//GEN-LAST:event_myButton2ActionPerformed

    private void myButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButton1ActionPerformed
        //co.agregarProductoOrdenSalida(tblOrdenesSalida, txtProductoID, cbProductoOrdenesSalida, txtCantidad, cbSucursalOrdenesSalida, cbCategoriaOrdenesSalida, txtExistencia);
        co.DevolucionProductos(cbSucursalDevolucion, txtProductoID, txtCantidadDevolver);
        co.guardarDevolucion(cbSucursalDevolucion, cbProductoDevolucion, txtMotivo, txtCantidadDevolver, txtFechaDev, txtProductoID, txtProvID);
    }//GEN-LAST:event_myButton1ActionPerformed

    private void cbCategoriaDevolucion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCategoriaDevolucion1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbCategoriaDevolucion1ActionPerformed

    private void txtNombreProducActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreProducActionPerformed

    }//GEN-LAST:event_txtNombreProducActionPerformed

    private void txtNombreProducKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreProducKeyReleased
        if (txtNombreProduc.getText().isBlank()) {
            co.LimpiarComboBox(cbProductoDevolucion);
        } else {
            co.RellenarComboBoxProductosDevoluciones(txtNombreProduc.getText(), cbProductoDevolucion);
        }
    }//GEN-LAST:event_txtNombreProducKeyReleased

    private void cbSucursalDevolucionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSucursalDevolucionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbSucursalDevolucionActionPerformed

    private void cbProductoDevolucionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbProductoDevolucionMouseClicked
    }//GEN-LAST:event_cbProductoDevolucionMouseClicked

    private void cbProductoDevolucionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbProductoDevolucionMousePressed
    }//GEN-LAST:event_cbProductoDevolucionMousePressed

    private void cbProductoDevolucionItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbProductoDevolucionItemStateChanged
        
    }//GEN-LAST:event_cbProductoDevolucionItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbCategoriaDevolucion1;
    private javax.swing.JComboBox<String> cbProductoDevolucion;
    private javax.swing.JComboBox<String> cbSucursalDevolucion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private metodos.MyButton myButton1;
    private metodos.MyButton myButton2;
    public javax.swing.JPanel pnlDevoluciones;
    private javax.swing.JTextField txtCantidadDevolver;
    private com.toedter.calendar.JDateChooser txtFechaDev;
    private javax.swing.JTextField txtMotivo;
    private javax.swing.JTextField txtNombreProduc;
    private javax.swing.JTextField txtProductoID;
    private javax.swing.JTextField txtProvID;
    // End of variables declaration//GEN-END:variables
}
