/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package paneles;

import Controlador.ControlOrdenes;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.LayoutManager;
import java.awt.RenderingHints;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author David Membreño
 */
public class pnlAgregarOrdenEntrada extends javax.swing.JPanel {

    ControlOrdenes co = new ControlOrdenes();

    public pnlAgregarOrdenEntrada() {
        initComponents();
        co.RellenarCombo("Sucursal", "Ciudad", cbSucursalOrdenEntrada);
        co.RellenarCombo("categoria", "Nombre", cbCategoriaOrdenesEntrada);
        //TextPrompt pClienteID = new TextPrompt("Identificador del cliente", txtClienteID);
        //TextPrompt pNombreC = new TextPrompt("Nombre del cliente", txtNombreCliente);
        //TextPrompt pDNIC = new TextPrompt("Numero de identidad del cliente", txtDNI);
        //TextPrompt pEmailC = new TextPrompt("Email del cliente (Opcional)", txtEmail);
        //TextPrompt pRTNC = new TextPrompt("RTN del cliente (Opcional)", txtRTN);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlOrdenesEntrada = new RoundedPanel(20, Color.WHITE);
        jLabel1 = new javax.swing.JLabel();
        txtNombreProduc = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        myButton2 = new metodos.MyButton();
        txtProductoID = new javax.swing.JTextField();
        myButton3 = new metodos.MyButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblOrdenEntrada = new javax.swing.JTable();
        myButton5 = new metodos.MyButton();
        myButton6 = new metodos.MyButton();
        jLabel7 = new javax.swing.JLabel();
        txtProveedor = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtProveedorID = new javax.swing.JTextField();
        cbSucursalOrdenEntrada = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        txtFechaExp = new com.toedter.calendar.JDateChooser();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        cbCategoriaOrdenesEntrada = new javax.swing.JComboBox<>();
        jLabel45 = new javax.swing.JLabel();
        cbProductoOrdenesEntrada = new javax.swing.JComboBox<>();
        jLabel46 = new javax.swing.JLabel();
        txtPrecioU = new javax.swing.JTextField();

        pnlOrdenesEntrada.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 18)); // NOI18N
        jLabel1.setText("Agregar Orden de Entrada");
        pnlOrdenesEntrada.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        txtNombreProduc.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        txtNombreProduc.setForeground(new java.awt.Color(102, 102, 102));
        txtNombreProduc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNombreProducKeyReleased(evt);
            }
        });
        pnlOrdenesEntrada.add(txtNombreProduc, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 70, 320, 37));

        jLabel4.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        jLabel4.setText("ProductoID:");
        pnlOrdenesEntrada.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 30, -1, -1));

        jLabel5.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        jLabel5.setText("Precio:");
        pnlOrdenesEntrada.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 140, -1, -1));

        jLabel6.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        jLabel6.setText("Cantidad a solicitar:");
        pnlOrdenesEntrada.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 140, -1, -1));

        txtCantidad.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        txtCantidad.setForeground(new java.awt.Color(102, 102, 102));
        pnlOrdenesEntrada.add(txtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 130, 100, 37));

        myButton2.setForeground(new java.awt.Color(255, 255, 255));
        myButton2.setText("Cancelar pedido");
        myButton2.setBorderColor(new java.awt.Color(102, 160, 255));
        myButton2.setColor(new java.awt.Color(102, 160, 255));
        myButton2.setColorClick(new java.awt.Color(19, 102, 217));
        myButton2.setColorOver(new java.awt.Color(183, 207, 255));
        myButton2.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 14)); // NOI18N
        myButton2.setRadius(10);
        myButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myButton2ActionPerformed(evt);
            }
        });
        pnlOrdenesEntrada.add(myButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 580, 220, 40));

        txtProductoID.setEditable(false);
        txtProductoID.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        txtProductoID.setForeground(new java.awt.Color(102, 102, 102));
        pnlOrdenesEntrada.add(txtProductoID, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 20, 80, 37));

        myButton3.setBackground(new java.awt.Color(19, 102, 217));
        myButton3.setForeground(new java.awt.Color(255, 255, 255));
        myButton3.setText("Confirmar pedido");
        myButton3.setBorderColor(new java.awt.Color(19, 102, 217));
        myButton3.setColor(new java.awt.Color(19, 102, 217));
        myButton3.setColorClick(new java.awt.Color(19, 102, 217));
        myButton3.setColorOver(new java.awt.Color(66, 139, 225));
        myButton3.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 14)); // NOI18N
        myButton3.setRadius(10);
        myButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myButton3ActionPerformed(evt);
            }
        });
        pnlOrdenesEntrada.add(myButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 580, 220, 40));

        tblOrdenEntrada.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ProductoID", "Producto", "Precio", "Cantidad", "Fecha Expiración", "ProveedorID", "Proveedor", "Sucursal"
            }
        ));
        jScrollPane1.setViewportView(tblOrdenEntrada);

        pnlOrdenesEntrada.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 1310, 310));

        myButton5.setBackground(new java.awt.Color(19, 102, 217));
        myButton5.setForeground(new java.awt.Color(255, 255, 255));
        myButton5.setText("Agregar producto");
        myButton5.setBorderColor(new java.awt.Color(19, 102, 217));
        myButton5.setColor(new java.awt.Color(19, 102, 217));
        myButton5.setColorClick(new java.awt.Color(19, 102, 217));
        myButton5.setColorOver(new java.awt.Color(66, 139, 225));
        myButton5.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 14)); // NOI18N
        myButton5.setRadius(10);
        myButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myButton5ActionPerformed(evt);
            }
        });
        pnlOrdenesEntrada.add(myButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 190, 210, 40));

        myButton6.setForeground(new java.awt.Color(255, 255, 255));
        myButton6.setText("Eliminar producto");
        myButton6.setBorderColor(new java.awt.Color(102, 160, 255));
        myButton6.setColor(new java.awt.Color(102, 160, 255));
        myButton6.setColorClick(new java.awt.Color(19, 102, 217));
        myButton6.setColorOver(new java.awt.Color(183, 207, 255));
        myButton6.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 14)); // NOI18N
        myButton6.setRadius(10);
        myButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myButton6ActionPerformed(evt);
            }
        });
        pnlOrdenesEntrada.add(myButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 190, 210, 40));

        jLabel7.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        jLabel7.setText("ProveedorID:");
        pnlOrdenesEntrada.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        txtProveedor.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        txtProveedor.setForeground(new java.awt.Color(102, 102, 102));
        txtProveedor.setEnabled(false);
        pnlOrdenesEntrada.add(txtProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, 260, 37));

        jLabel3.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        jLabel3.setText("Fecha de expiración:");
        pnlOrdenesEntrada.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 140, -1, -1));

        txtProveedorID.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        txtProveedorID.setForeground(new java.awt.Color(102, 102, 102));
        txtProveedorID.setEnabled(false);
        pnlOrdenesEntrada.add(txtProveedorID, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 80, 37));

        cbSucursalOrdenEntrada.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 12)); // NOI18N
        cbSucursalOrdenEntrada.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar Sucursal" }));
        cbSucursalOrdenEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSucursalOrdenEntradaActionPerformed(evt);
            }
        });
        pnlOrdenesEntrada.add(cbSucursalOrdenEntrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 230, -1));

        jLabel9.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        jLabel9.setText("Proveedor:");
        pnlOrdenesEntrada.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, -1, -1));
        pnlOrdenesEntrada.add(txtFechaExp, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 130, 170, 40));

        jLabel43.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 14)); // NOI18N
        jLabel43.setText("Seleccionar Sucursal:");
        pnlOrdenesEntrada.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, 20));

        jLabel44.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 14)); // NOI18N
        jLabel44.setText("Producto:");
        pnlOrdenesEntrada.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 80, -1, 20));

        cbCategoriaOrdenesEntrada.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 12)); // NOI18N
        cbCategoriaOrdenesEntrada.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar Categoría" }));
        cbCategoriaOrdenesEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCategoriaOrdenesEntradaActionPerformed(evt);
            }
        });
        pnlOrdenesEntrada.add(cbCategoriaOrdenesEntrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, 300, 20));

        jLabel45.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 14)); // NOI18N
        jLabel45.setText("Seleccionar Producto:");
        pnlOrdenesEntrada.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 80, -1, 20));

        cbProductoOrdenesEntrada.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 12)); // NOI18N
        cbProductoOrdenesEntrada.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar Producto" }));
        cbProductoOrdenesEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbProductoOrdenesEntradaActionPerformed(evt);
            }
        });
        pnlOrdenesEntrada.add(cbProductoOrdenesEntrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 80, 280, 20));

        jLabel46.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 14)); // NOI18N
        jLabel46.setText("Seleccionar Categoria:");
        pnlOrdenesEntrada.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, -1, 20));

        txtPrecioU.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        txtPrecioU.setForeground(new java.awt.Color(102, 102, 102));
        pnlOrdenesEntrada.add(txtPrecioU, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 130, 100, 37));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlOrdenesEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 1352, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlOrdenesEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 631, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void myButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButton2ActionPerformed
        LimpiarPanel();
    }//GEN-LAST:event_myButton2ActionPerformed

    private void myButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButton6ActionPerformed
        co.EliminarRegistroTabla(tblOrdenEntrada);
    }//GEN-LAST:event_myButton6ActionPerformed

    private void cbSucursalOrdenEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSucursalOrdenEntradaActionPerformed
        //co.RellenarComboProductos(cbCategoriaOrdenesEntrada.getSelectedIndex(), cbSucursalOrdenEntrada.getSelectedIndex(), cbProductoOrdenesEntrada);
        if (cbSucursalOrdenEntrada.getSelectedIndex() == 0 && txtNombreProduc.getText().isBlank()) {
            co.LimpiarComboBox(cbProductoOrdenesEntrada);
        } else {
            co.RellenarComboBoxProductos(txtNombreProduc.getText(), cbSucursalOrdenEntrada.getSelectedIndex(), cbProductoOrdenesEntrada);
        }
//        try {
        //            ci.LlenarTablaInventario(tblInventario, cbSucursalInventario.getSelectedIndex());
        //        } catch (SQLException ex) {
        //            Logger.getLogger(pnlInventario.class.getName()).log(Level.SEVERE, null, ex);
        //        }
    }//GEN-LAST:event_cbSucursalOrdenEntradaActionPerformed

    private void myButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButton5ActionPerformed
        co.agregarProducto(tblOrdenEntrada, txtProductoID, cbProductoOrdenesEntrada, txtProveedorID, txtProveedor, txtPrecioU, txtCantidad, cbSucursalOrdenEntrada,txtFechaExp, cbCategoriaOrdenesEntrada);
        //LimpiarTextFields();

    }//GEN-LAST:event_myButton5ActionPerformed

    private void myButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButton3ActionPerformed
        co.guardarOrdenEntrada(cbSucursalOrdenEntrada);
        co.guardarOrdenEntradaDetalle(tblOrdenEntrada, cbSucursalOrdenEntrada);
        LimpiarPanel();
    }//GEN-LAST:event_myButton3ActionPerformed

    private void cbCategoriaOrdenesEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCategoriaOrdenesEntradaActionPerformed
        co.RellenarComboProductos(cbCategoriaOrdenesEntrada.getSelectedIndex(), cbSucursalOrdenEntrada.getSelectedIndex(), cbProductoOrdenesEntrada);
//        co.RellenarComboProductos(cbCategoriaOrdenesSalida.getSelectedIndex(), cbSucursalOrdenesSalida.getSelectedIndex(), cbProductoOrdenesSalida);
    }//GEN-LAST:event_cbCategoriaOrdenesEntradaActionPerformed

    private void cbProductoOrdenesEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbProductoOrdenesEntradaActionPerformed
        co.BuscarProductosOrdenEntrada(cbProductoOrdenesEntrada, cbSucursalOrdenEntrada, txtProveedorID, txtProveedor, txtProductoID);
        //      co.BuscarProductosOrdenSalida(cbProductoOrdenesSalida, cbSucursalOrdenesSalida, txtExistencia, txtProductoID);
    }//GEN-LAST:event_cbProductoOrdenesEntradaActionPerformed

    private void txtNombreProducKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreProducKeyReleased
        if (cbSucursalOrdenEntrada.getSelectedIndex() == 0 && txtNombreProduc.getText().isBlank()) {
            co.LimpiarComboBox(cbProductoOrdenesEntrada);
        } else {
            co.RellenarComboBoxProductos(txtNombreProduc.getText(), cbSucursalOrdenEntrada.getSelectedIndex(), cbProductoOrdenesEntrada);
        }
//co.RellenarComboBoxProductos(txtNombreProduc.getText(), cbSucursalOrdenEntrada.getSelectedIndex(), cbProductoOrdenesEntrada);
    }//GEN-LAST:event_txtNombreProducKeyReleased

    private void LimpiarPanel() {
        cbSucursalOrdenEntrada.setSelectedIndex(0);
        LimpiarTextFields();
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ProductoID");
        model.addColumn("Producto");
        model.addColumn("Precio");
        model.addColumn("Cantidad");
        model.addColumn("ProveedorID");
        model.addColumn("Proveedor");
        model.addColumn("Sucursal");

        tblOrdenEntrada.setModel(model);

    }

    private void LimpiarTextFields() {
//        txtProductoID.setText("");
        txtCantidad.setText("");
        txtNombreProduc.setText("");
        // txtProducto.setText("");
        txtProveedor.setText("");
        txtProveedorID.setText("");

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbCategoriaOrdenesEntrada;
    private javax.swing.JComboBox<String> cbProductoOrdenesEntrada;
    private javax.swing.JComboBox<String> cbSucursalOrdenEntrada;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private metodos.MyButton myButton2;
    private metodos.MyButton myButton3;
    private metodos.MyButton myButton5;
    private metodos.MyButton myButton6;
    public javax.swing.JPanel pnlOrdenesEntrada;
    private javax.swing.JTable tblOrdenEntrada;
    private javax.swing.JTextField txtCantidad;
    private com.toedter.calendar.JDateChooser txtFechaExp;
    private javax.swing.JTextField txtNombreProduc;
    private javax.swing.JTextField txtPrecioU;
    public javax.swing.JTextField txtProductoID;
    private javax.swing.JTextField txtProveedor;
    private javax.swing.JTextField txtProveedorID;
    // End of variables declaration//GEN-END:variables

    class RoundedPanel extends JPanel {

        private Color backgroundColor;
        private int cornerRadius = 15;

        public RoundedPanel(LayoutManager layout, int radius) {
            super(layout);
            cornerRadius = radius;
        }

        public RoundedPanel(LayoutManager layout, int radius, Color bgColor) {
            super(layout);
            cornerRadius = radius;
            backgroundColor = bgColor;
        }

        public RoundedPanel(int radius) {
            super();
            cornerRadius = radius;

        }

        public RoundedPanel(int radius, Color bgColor) {
            super();
            cornerRadius = radius;
            backgroundColor = bgColor;
        }

        @Override
        protected void paintComponent(Graphics g) {
            super.paintComponent(g);
            Dimension arcs = new Dimension(cornerRadius, cornerRadius);
            int width = getWidth();
            int height = getHeight();
            Graphics2D graphics = (Graphics2D) g;
            graphics.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
            //Draws the rounded panel with borders.
            if (backgroundColor != null) {
                graphics.setColor(backgroundColor);
            } else {
                graphics.setColor(getBackground());
            }
            graphics.fillRoundRect(0, 0, width - 1, height - 1, arcs.width, arcs.height); //paint background
            graphics.setColor(getForeground());
//            graphics.drawRoundRect(0, 0, width-1, height-1, arcs.width, arcs.height); //paint border
//             
        }

    }
}
