/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package paneles;

import Controlador.ControlOrdenes;
import metodos.TextPrompt;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.LayoutManager;
import java.awt.RenderingHints;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author David Membreño
 */
public class pnlAgregarOrdenSalida extends javax.swing.JPanel {

    /**
     * Creates new form pnlAgregarCliente
     */
    ControlOrdenes co =  new ControlOrdenes();
    public pnlAgregarOrdenSalida() {
        initComponents();
        co.RellenarCombo("Sucursal", "Ciudad", cbSucursalOrdenesSalida);
        co.RellenarCombo("categoria", "Nombre", cbCategoriaOrdenesSalida);
        //TextPrompt pClienteID = new TextPrompt("Identificador del cliente", txtClienteID);
        //TextPrompt pNombreC = new TextPrompt("Nombre del cliente", txtNombreCliente);
        //TextPrompt pDNIC = new TextPrompt("Numero de identidad del cliente", txtDNI);
        //TextPrompt pEmailC = new TextPrompt("Email del cliente (Opcional)", txtEmail);
        //TextPrompt pRTNC = new TextPrompt("RTN del cliente (Opcional)", txtRTN);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlOrdenSalida = new RoundedPanel(20, Color.WHITE);
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        myButton2 = new metodos.MyButton();
        txtProductoID = new javax.swing.JTextField();
        myButton3 = new metodos.MyButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblOrdenesSalida = new javax.swing.JTable();
        myButton5 = new metodos.MyButton();
        myButton6 = new metodos.MyButton();
        cbSucursalOrdenesSalida = new javax.swing.JComboBox<>();
        jLabel43 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtExistencia = new javax.swing.JTextField();
        cbCategoriaOrdenesSalida = new javax.swing.JComboBox<>();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        cbProductoOrdenesSalida = new javax.swing.JComboBox<>();
        txtNombreProduc = new javax.swing.JTextField();
        jLabel46 = new javax.swing.JLabel();

        pnlOrdenSalida.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 18)); // NOI18N
        jLabel1.setText("Agregar Orden de Salida");
        pnlOrdenSalida.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jLabel4.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        jLabel4.setText("ProductoID:");
        pnlOrdenSalida.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 40, -1, -1));

        jLabel6.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        jLabel6.setText("Cantidad solicitada:");
        pnlOrdenSalida.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 140, -1, -1));

        txtCantidad.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        txtCantidad.setForeground(new java.awt.Color(102, 102, 102));
        pnlOrdenSalida.add(txtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 130, 240, 37));

        myButton2.setForeground(new java.awt.Color(255, 255, 255));
        myButton2.setText("Cancelar pedido");
        myButton2.setBorderColor(new java.awt.Color(102, 160, 255));
        myButton2.setColor(new java.awt.Color(102, 160, 255));
        myButton2.setColorClick(new java.awt.Color(19, 102, 217));
        myButton2.setColorOver(new java.awt.Color(183, 207, 255));
        myButton2.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 14)); // NOI18N
        myButton2.setRadius(10);
        myButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myButton2ActionPerformed(evt);
            }
        });
        pnlOrdenSalida.add(myButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 520, 170, 40));

        txtProductoID.setEditable(false);
        txtProductoID.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        txtProductoID.setForeground(new java.awt.Color(102, 102, 102));
        pnlOrdenSalida.add(txtProductoID, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 30, 100, 37));

        myButton3.setBackground(new java.awt.Color(19, 102, 217));
        myButton3.setForeground(new java.awt.Color(255, 255, 255));
        myButton3.setText("Confirmar pedido");
        myButton3.setBorderColor(new java.awt.Color(19, 102, 217));
        myButton3.setColor(new java.awt.Color(19, 102, 217));
        myButton3.setColorClick(new java.awt.Color(19, 102, 217));
        myButton3.setColorOver(new java.awt.Color(66, 139, 225));
        myButton3.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 14)); // NOI18N
        myButton3.setRadius(10);
        myButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myButton3ActionPerformed(evt);
            }
        });
        pnlOrdenSalida.add(myButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 520, 170, 40));

        tblOrdenesSalida.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ProductoID", "Producto", "Cantidad", "Sucursal"
            }
        ));
        jScrollPane1.setViewportView(tblOrdenesSalida);

        pnlOrdenSalida.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 1250, 310));

        myButton5.setBackground(new java.awt.Color(19, 102, 217));
        myButton5.setForeground(new java.awt.Color(255, 255, 255));
        myButton5.setText("Agregar producto");
        myButton5.setBorderColor(new java.awt.Color(19, 102, 217));
        myButton5.setColor(new java.awt.Color(19, 102, 217));
        myButton5.setColorClick(new java.awt.Color(19, 102, 217));
        myButton5.setColorOver(new java.awt.Color(66, 139, 225));
        myButton5.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 14)); // NOI18N
        myButton5.setRadius(10);
        myButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myButton5ActionPerformed(evt);
            }
        });
        pnlOrdenSalida.add(myButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 130, 200, 40));

        myButton6.setForeground(new java.awt.Color(255, 255, 255));
        myButton6.setText("Eliminar producto");
        myButton6.setBorderColor(new java.awt.Color(102, 160, 255));
        myButton6.setColor(new java.awt.Color(102, 160, 255));
        myButton6.setColorClick(new java.awt.Color(19, 102, 217));
        myButton6.setColorOver(new java.awt.Color(183, 207, 255));
        myButton6.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 14)); // NOI18N
        myButton6.setRadius(10);
        myButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myButton6ActionPerformed(evt);
            }
        });
        pnlOrdenSalida.add(myButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 130, 200, 40));

        cbSucursalOrdenesSalida.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 12)); // NOI18N
        cbSucursalOrdenesSalida.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar Sucursal" }));
        cbSucursalOrdenesSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSucursalOrdenesSalidaActionPerformed(evt);
            }
        });
        pnlOrdenSalida.add(cbSucursalOrdenesSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 230, 20));

        jLabel43.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 14)); // NOI18N
        jLabel43.setText("Seleccionar Sucursal:");
        pnlOrdenSalida.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, 20));

        jLabel9.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        jLabel9.setText("Existencia:");
        pnlOrdenSalida.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        txtExistencia.setEditable(false);
        txtExistencia.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        txtExistencia.setForeground(new java.awt.Color(102, 102, 102));
        pnlOrdenSalida.add(txtExistencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 260, 37));

        cbCategoriaOrdenesSalida.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 12)); // NOI18N
        cbCategoriaOrdenesSalida.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar Categoría" }));
        cbCategoriaOrdenesSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCategoriaOrdenesSalidaActionPerformed(evt);
            }
        });
        pnlOrdenSalida.add(cbCategoriaOrdenesSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, 250, 20));

        jLabel44.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 14)); // NOI18N
        jLabel44.setText("Seleccionar Categoria:");
        pnlOrdenSalida.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, -1, 20));

        jLabel45.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 14)); // NOI18N
        jLabel45.setText("Seleccionar Producto:");
        pnlOrdenSalida.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 80, -1, 20));

        cbProductoOrdenesSalida.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 12)); // NOI18N
        cbProductoOrdenesSalida.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar Producto" }));
        cbProductoOrdenesSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbProductoOrdenesSalidaActionPerformed(evt);
            }
        });
        pnlOrdenSalida.add(cbProductoOrdenesSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 80, 280, 20));

        txtNombreProduc.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        txtNombreProduc.setForeground(new java.awt.Color(102, 102, 102));
        txtNombreProduc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNombreProducKeyReleased(evt);
            }
        });
        pnlOrdenSalida.add(txtNombreProduc, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 70, 320, 37));

        jLabel46.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 14)); // NOI18N
        jLabel46.setText("Producto:");
        pnlOrdenSalida.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 80, -1, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlOrdenSalida, javax.swing.GroupLayout.DEFAULT_SIZE, 1287, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlOrdenSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 577, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void myButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButton2ActionPerformed
        LimpiarPanel();
    }//GEN-LAST:event_myButton2ActionPerformed

    private void myButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButton6ActionPerformed
        co.EliminarRegistroTabla(tblOrdenesSalida);
    }//GEN-LAST:event_myButton6ActionPerformed

    private void cbSucursalOrdenesSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSucursalOrdenesSalidaActionPerformed
//        co.BuscarProductoOrdenSalida(txtProductoID, txtProducto, cbSucursalOrdenesSalida, txtExistencia);
        //co.RellenarComboProductos(cbCategoriaOrdenesSalida.getSelectedIndex(), cbSucursalOrdenesSalida.getSelectedIndex(), cbProductoOrdenesSalida);
        co.RellenarComboBoxProductos(txtNombreProduc.getText(), cbSucursalOrdenesSalida.getSelectedIndex(), cbProductoOrdenesSalida);
    }//GEN-LAST:event_cbSucursalOrdenesSalidaActionPerformed

    private void myButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButton5ActionPerformed
        co.agregarProductoOrdenSalida(tblOrdenesSalida, txtProductoID, cbProductoOrdenesSalida, txtCantidad, cbSucursalOrdenesSalida, cbCategoriaOrdenesSalida, txtExistencia);
        //limpiarTextFields();
    }//GEN-LAST:event_myButton5ActionPerformed

    private void myButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButton3ActionPerformed
        co.guardarOrdenSalida();
        co.guardarOrdenSalidaDetalle(tblOrdenesSalida, cbSucursalOrdenesSalida);
        co.ActualizarExistencia(tblOrdenesSalida, cbSucursalOrdenesSalida);
        LimpiarPanel();
    }//GEN-LAST:event_myButton3ActionPerformed

    private void cbCategoriaOrdenesSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCategoriaOrdenesSalidaActionPerformed
        co.RellenarComboProductos(cbCategoriaOrdenesSalida.getSelectedIndex(), cbSucursalOrdenesSalida.getSelectedIndex(), cbProductoOrdenesSalida);
    }//GEN-LAST:event_cbCategoriaOrdenesSalidaActionPerformed

    private void cbProductoOrdenesSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbProductoOrdenesSalidaActionPerformed
        co.BuscarProductosOrdenSalida(cbProductoOrdenesSalida, cbSucursalOrdenesSalida, txtExistencia, txtProductoID);
    }//GEN-LAST:event_cbProductoOrdenesSalidaActionPerformed

    private void txtNombreProducKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreProducKeyReleased
        co.RellenarComboBoxProductos(txtNombreProduc.getText(), cbSucursalOrdenesSalida.getSelectedIndex(), cbProductoOrdenesSalida);
    }//GEN-LAST:event_txtNombreProducKeyReleased

    private void limpiarTextFields() {
        txtProductoID.setText("");
        //txtProducto.setText("");
        txtCantidad.setText("");
    }

    private void LimpiarPanel(){
        limpiarTextFields();
        cbSucursalOrdenesSalida.setSelectedIndex(0);
        
                DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ProductoID");
        model.addColumn("Producto");
        model.addColumn("Cantidad");
        model.addColumn("Sucursal");
        
       tblOrdenesSalida.setModel(model);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbCategoriaOrdenesSalida;
    private javax.swing.JComboBox<String> cbProductoOrdenesSalida;
    private javax.swing.JComboBox<String> cbSucursalOrdenesSalida;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private metodos.MyButton myButton2;
    private metodos.MyButton myButton3;
    private metodos.MyButton myButton5;
    private metodos.MyButton myButton6;
    public javax.swing.JPanel pnlOrdenSalida;
    private javax.swing.JTable tblOrdenesSalida;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtExistencia;
    private javax.swing.JTextField txtNombreProduc;
    private javax.swing.JTextField txtProductoID;
    // End of variables declaration//GEN-END:variables

    class RoundedPanel extends JPanel {

        private Color backgroundColor;
        private int cornerRadius = 15;

        public RoundedPanel(LayoutManager layout, int radius) {
            super(layout);
            cornerRadius = radius;
        }

        public RoundedPanel(LayoutManager layout, int radius, Color bgColor) {
            super(layout);
            cornerRadius = radius;
            backgroundColor = bgColor;
        }

        public RoundedPanel(int radius) {
            super();
            cornerRadius = radius;

        }

        public RoundedPanel(int radius, Color bgColor) {
            super();
            cornerRadius = radius;
            backgroundColor = bgColor;
        }

        @Override
        protected void paintComponent(Graphics g) {
            super.paintComponent(g);
            Dimension arcs = new Dimension(cornerRadius, cornerRadius);
            int width = getWidth();
            int height = getHeight();
            Graphics2D graphics = (Graphics2D) g;
            graphics.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
            //Draws the rounded panel with borders.
            if (backgroundColor != null) {
                graphics.setColor(backgroundColor);
            } else {
                graphics.setColor(getBackground());
            }
            graphics.fillRoundRect(0, 0, width - 1, height - 1, arcs.width, arcs.height); //paint background
            graphics.setColor(getForeground());
//            graphics.drawRoundRect(0, 0, width-1, height-1, arcs.width, arcs.height); //paint border
//             
        }

    }
}
