/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package paneles;

import Controlador.ControlProveedores;
import Modelo.Proveedores;
import metodos.TextPrompt;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.LayoutManager;
import java.awt.RenderingHints;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
/**
 *
 * @author David Membreño
 */
public class pnlAgregarProveedor extends javax.swing.JPanel {

    Proveedores proveedor = new Proveedores();
    public pnlAgregarProveedor() {
        initComponents();
        
        TextPrompt pNombreP = new TextPrompt("Ingrese el nombre del proveedor", txtNombreProveedor);
        TextPrompt pDireccion = new TextPrompt("Ingrese la dirección del proveedor", txtDireccion);
        TextPrompt pDNIC = new TextPrompt("Ingrese el RTN", txtRTN);
        TextPrompt pContacto = new TextPrompt("Ingrese el contacto del proveedor", txtContacto);
        TextPrompt pCorreo = new TextPrompt("Ingrese el correo del proveedor", txtCorreo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlProveedores = new RoundedPanel(20, Color.WHITE);
        jLabel1 = new javax.swing.JLabel();
        txtContacto = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        myButton1 = new metodos.MyButton();
        myButton2 = new metodos.MyButton();
        txtNombreProveedor = new javax.swing.JTextField();
        txtRTN = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();

        pnlProveedores.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 18)); // NOI18N
        jLabel1.setText("Agregar proveedor");
        pnlProveedores.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        txtContacto.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        txtContacto.setForeground(new java.awt.Color(102, 102, 102));
        pnlProveedores.add(txtContacto, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, 342, 37));

        jLabel3.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        jLabel3.setText("Nombre del Proveedor");
        pnlProveedores.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        jLabel4.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        jLabel4.setText("RTN");
        pnlProveedores.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        jLabel5.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        jLabel5.setText("Contacto");
        pnlProveedores.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));

        jLabel6.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        jLabel6.setText("Correo");
        pnlProveedores.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, -1));

        txtCorreo.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        txtCorreo.setForeground(new java.awt.Color(102, 102, 102));
        pnlProveedores.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, 342, 37));

        myButton1.setBackground(new java.awt.Color(19, 102, 217));
        myButton1.setForeground(new java.awt.Color(255, 255, 255));
        myButton1.setText("Añadir Proveedor");
        myButton1.setBorderColor(new java.awt.Color(19, 102, 217));
        myButton1.setColor(new java.awt.Color(19, 102, 217));
        myButton1.setColorClick(new java.awt.Color(19, 102, 217));
        myButton1.setColorOver(new java.awt.Color(66, 139, 225));
        myButton1.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 14)); // NOI18N
        myButton1.setRadius(10);
        myButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myButton1ActionPerformed(evt);
            }
        });
        pnlProveedores.add(myButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 360, 160, 40));

        myButton2.setForeground(new java.awt.Color(255, 255, 255));
        myButton2.setText("Descartar");
        myButton2.setBorderColor(new java.awt.Color(102, 160, 255));
        myButton2.setColor(new java.awt.Color(102, 160, 255));
        myButton2.setColorClick(new java.awt.Color(19, 102, 217));
        myButton2.setColorOver(new java.awt.Color(183, 207, 255));
        myButton2.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 14)); // NOI18N
        myButton2.setRadius(10);
        myButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myButton2ActionPerformed(evt);
            }
        });
        pnlProveedores.add(myButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 360, 170, 40));

        txtNombreProveedor.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        txtNombreProveedor.setForeground(new java.awt.Color(102, 102, 102));
        txtNombreProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreProveedorActionPerformed(evt);
            }
        });
        pnlProveedores.add(txtNombreProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, 342, 37));

        txtRTN.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        txtRTN.setForeground(new java.awt.Color(102, 102, 102));
        pnlProveedores.add(txtRTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 342, 37));

        jLabel7.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        jLabel7.setText("Dirección");
        pnlProveedores.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        txtDireccion.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        txtDireccion.setForeground(new java.awt.Color(102, 102, 102));
        txtDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDireccionActionPerformed(evt);
            }
        });
        pnlProveedores.add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 342, 37));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlProveedores, javax.swing.GroupLayout.PREFERRED_SIZE, 554, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlProveedores, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void myButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButton2ActionPerformed
        LimpiarInputs();
    }//GEN-LAST:event_myButton2ActionPerformed

    private void txtNombreProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreProveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreProveedorActionPerformed

    private void myButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButton1ActionPerformed
        ControlProveedores cp = new ControlProveedores();
        cp.guardarProveedor(txtNombreProveedor, txtDireccion, txtRTN, txtContacto, txtCorreo);
        //LimpiarInputs();
        try {
            pnlProveedores pnlProv = new pnlProveedores();
            cp.LlenarTablaProveedores(pnlProv.tableProveedores);
        } catch (SQLException ex) {
            Logger.getLogger(pnlAgregarProveedor.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_myButton1ActionPerformed

    private void LimpiarInputs(){
        txtNombreProveedor.setText("");
        txtRTN.setText("");
        txtDireccion.setText("");
        txtCorreo.setText("");
        txtContacto.setText("");
    }
    private void txtDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDireccionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private metodos.MyButton myButton1;
    private metodos.MyButton myButton2;
    public javax.swing.JPanel pnlProveedores;
    private javax.swing.JTextField txtContacto;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtNombreProveedor;
    private javax.swing.JTextField txtRTN;
    // End of variables declaration//GEN-END:variables
    
    class RoundedPanel extends JPanel {

        private Color backgroundColor;
        private int cornerRadius = 15;

        public RoundedPanel(LayoutManager layout, int radius) {
            super(layout);
            cornerRadius = radius;
        }

        public RoundedPanel(LayoutManager layout, int radius, Color bgColor) {
            super(layout);
            cornerRadius = radius;
            backgroundColor = bgColor;
        }

        public RoundedPanel(int radius) {
            super();
            cornerRadius = radius;

        }

        public RoundedPanel(int radius, Color bgColor) {
            super();
            cornerRadius = radius;
            backgroundColor = bgColor;
        }

        @Override
        protected void paintComponent(Graphics g) {
            super.paintComponent(g);
            Dimension arcs = new Dimension(cornerRadius, cornerRadius);
            int width = getWidth();
            int height = getHeight();
            Graphics2D graphics = (Graphics2D) g;
            graphics.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
            //Draws the rounded panel with borders.
            if (backgroundColor != null) {
                graphics.setColor(backgroundColor);
            } else {
                graphics.setColor(getBackground());
            }
            graphics.fillRoundRect(0, 0, width - 1, height - 1, arcs.width, arcs.height); //paint background
            graphics.setColor(getForeground());
//            graphics.drawRoundRect(0, 0, width-1, height-1, arcs.width, arcs.height); //paint border
//             
        }

    }
}
