/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package paneles;

import Controlador.ControlInventario;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.LayoutManager;
import java.awt.RenderingHints;
import javax.swing.JPanel;
//import metodos.TextPrompt;

/**
 *
 * @author David Membreño
 */
public class pnlNuevoProducto extends javax.swing.JPanel {

    ControlInventario ci = new ControlInventario();
    public pnlNuevoProducto() {
        initComponents();
        //TextPrompt pProducto = new TextPrompt("Ingrese nombre del producto", txtProducto);
        //TextPrompt pProductoID = new TextPrompt("Ingrese ID del producto", txtProductoID);
        //TextPrompt pPrecio = new TextPrompt("Ingrese el precio del producto", txtPrecio);
        //TextPrompt pCantidad = new TextPrompt("Ingrese cantidad", txtCantidad);
        //TextPrompt pValorU = new TextPrompt("Valor Umbral", txtValorUmbral);
       // TextPrompt pFechaE = new TextPrompt("Ingrese la fecha de expiración", txtFechaExpiracion);
       ci.RellenarCombo("Categoria", "Nombre", jcbCategoria);
       ci.RellenarCombo("Proveedor", "Nombre", jcbProveedor);
       //ci.RellenarCombo("Sucursal", "Ciudad", jcbSucursal);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        pnlProductoNuevo = new RoundedPanel(20, Color.WHITE);
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtProducto = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jcbProveedor = new javax.swing.JComboBox<>();
        jcbCategoria = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        myButton1 = new metodos.MyButton();
        myButton2 = new metodos.MyButton();
        jLabel9 = new javax.swing.JLabel();
        txtStockMinimo = new javax.swing.JTextField();

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        pnlProductoNuevo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 18)); // NOI18N
        jLabel1.setText("Nuevo Producto");
        pnlProductoNuevo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        jLabel2.setText("Nombre");
        pnlProductoNuevo.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        txtProducto.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        pnlProductoNuevo.add(txtProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 342, 37));

        jLabel4.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        jLabel4.setText("Categoria");
        pnlProductoNuevo.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        jLabel5.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        jLabel5.setText("Proveedor");
        pnlProductoNuevo.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        jcbProveedor.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        jcbProveedor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione el proveedor" }));
        pnlProductoNuevo.add(jcbProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 340, 40));

        jcbCategoria.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        jcbCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione la categoria" }));
        pnlProductoNuevo.add(jcbCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 340, 40));

        jLabel6.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        jLabel6.setText("Precio");
        pnlProductoNuevo.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));

        txtPrecio.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        pnlProductoNuevo.add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 342, 37));

        myButton1.setBackground(new java.awt.Color(19, 102, 217));
        myButton1.setForeground(new java.awt.Color(255, 255, 255));
        myButton1.setText("Añadir Producto");
        myButton1.setBorderColor(new java.awt.Color(19, 102, 217));
        myButton1.setColor(new java.awt.Color(19, 102, 217));
        myButton1.setColorClick(new java.awt.Color(19, 102, 217));
        myButton1.setColorOver(new java.awt.Color(66, 139, 225));
        myButton1.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 14)); // NOI18N
        myButton1.setRadius(10);
        myButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myButton1ActionPerformed(evt);
            }
        });
        pnlProductoNuevo.add(myButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 360, 160, 40));

        myButton2.setForeground(new java.awt.Color(255, 255, 255));
        myButton2.setText("Descartar");
        myButton2.setBorderColor(new java.awt.Color(102, 160, 255));
        myButton2.setColor(new java.awt.Color(102, 160, 255));
        myButton2.setColorClick(new java.awt.Color(19, 102, 217));
        myButton2.setColorOver(new java.awt.Color(183, 207, 255));
        myButton2.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 14)); // NOI18N
        myButton2.setRadius(10);
        myButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myButton2ActionPerformed(evt);
            }
        });
        pnlProductoNuevo.add(myButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 360, 170, 40));

        jLabel9.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        jLabel9.setText("Existencia Minima:");
        pnlProductoNuevo.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, -1));

        txtStockMinimo.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        pnlProductoNuevo.add(txtStockMinimo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 300, 342, 37));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlProductoNuevo, javax.swing.GroupLayout.DEFAULT_SIZE, 554, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlProductoNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 9, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void myButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButton2ActionPerformed
        jcbCategoria.setSelectedIndex(0);
        jcbProveedor.setSelectedIndex(0);
        //jcbSucursal.setSelectedIndex(0);
        txtProducto.setText("");
        txtPrecio.setText("");
        //txtCantidad.setText("");
        txtStockMinimo.setText("");
        //txtFechaExpiracion.setDate(null);
    }//GEN-LAST:event_myButton2ActionPerformed

    private void myButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButton1ActionPerformed
        ControlInventario inventario =  new ControlInventario();
        inventario.guardarProductoDetalle(jcbProveedor, jcbCategoria, txtPrecio, txtStockMinimo, txtProducto);
    }//GEN-LAST:event_myButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    public javax.swing.JComboBox<String> jcbCategoria;
    public javax.swing.JComboBox<String> jcbProveedor;
    private metodos.MyButton myButton1;
    private metodos.MyButton myButton2;
    public javax.swing.JPanel pnlProductoNuevo;
    public javax.swing.JTextField txtPrecio;
    public javax.swing.JTextField txtProducto;
    public javax.swing.JTextField txtStockMinimo;
    // End of variables declaration//GEN-END:variables
    class RoundedPanel extends JPanel {

        private Color backgroundColor;
        private int cornerRadius = 15;

        public RoundedPanel(LayoutManager layout, int radius) {
            super(layout);
            cornerRadius = radius;
        }

        public RoundedPanel(LayoutManager layout, int radius, Color bgColor) {
            super(layout);
            cornerRadius = radius;
            backgroundColor = bgColor;
        }

        public RoundedPanel(int radius) {
            super();
            cornerRadius = radius;

        }

        public RoundedPanel(int radius, Color bgColor) {
            super();
            cornerRadius = radius;
            backgroundColor = bgColor;
        }

        @Override
        protected void paintComponent(Graphics g) {
            super.paintComponent(g);
            Dimension arcs = new Dimension(cornerRadius, cornerRadius);
            int width = getWidth();
            int height = getHeight();
            Graphics2D graphics = (Graphics2D) g;
            graphics.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
            //Draws the rounded panel with borders.
            if (backgroundColor != null) {
                graphics.setColor(backgroundColor);
            } else {
                graphics.setColor(getBackground());
            }
            graphics.fillRoundRect(0, 0, width - 1, height - 1, arcs.width, arcs.height); //paint background
            graphics.setColor(getForeground());
//            graphics.drawRoundRect(0, 0, width-1, height-1, arcs.width, arcs.height); //paint border
//             
        }

    }
}
