/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package paneles;

import Controlador.ControlOrdenes;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.LayoutManager;
import java.awt.RenderingHints;
import java.sql.SQLException;
import java.util.Enumeration;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;
import principal.Principal;

/**
 *
 * @author David Membreño
 */
public class pnlOrdenes extends javax.swing.JPanel {
    Principal p = new Principal();
    /**
     * Creates new form pnlOrdenes
     */
             
    ControlOrdenes co = new ControlOrdenes();          
    public pnlOrdenes() throws SQLException {
        initComponents();
        co.RellenarCombo("Sucursal", "Ciudad", cbSucursalOrdenes);
        co.RellenarCombo("Sucursal", "Ciudad", cbSucursalOrdenes1);
        co.LlenarTablaOrdenesEntrada(tblOrdenesEntrada, cbSucursalOrdenes.getSelectedIndex());
        co.LlenarTablaOrdenesSalida(tblOrdenesSalida, cbSucursalOrdenes1.getSelectedIndex());
        co.LlenarTablaDevolucionProductos(jTable1);
        
        adjustColumnWidths(tblOrdenesEntrada);
        adjustColumnWidths(tblOrdenesSalida);
    }
    

    private static void adjustColumnWidths(JTable table) {
        for (int columnIndex = 0; columnIndex < table.getColumnCount(); columnIndex++) {
            TableColumn column = table.getColumnModel().getColumn(columnIndex);
            int preferredWidth = 0;

            for (int rowIndex = 0; rowIndex < table.getRowCount(); rowIndex++) {
                TableCellRenderer cellRenderer = table.getCellRenderer(rowIndex, columnIndex);
                Component cellComponent = table.prepareRenderer(cellRenderer, rowIndex, columnIndex);
                preferredWidth = Math.max(preferredWidth, cellComponent.getPreferredSize().width);
            }

            column.setPreferredWidth(preferredWidth);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new RoundedPanel(20, Color.WHITE);
        myButton3 = new metodos.MyButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblOrdenesEntrada = new javax.swing.JTable();
        jLabel43 = new javax.swing.JLabel();
        cbSucursalOrdenes = new javax.swing.JComboBox<>();
        jLabel46 = new javax.swing.JLabel();
        txtBuscarOrden = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new RoundedPanel(20, Color.WHITE);
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jPanel7 = new RoundedPanel(20, Color.WHITE);
        jLabel41 = new javax.swing.JLabel();
        myButton8 = new metodos.MyButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblOrdenesSalida = new javax.swing.JTable();
        jLabel44 = new javax.swing.JLabel();
        cbSucursalOrdenes1 = new javax.swing.JComboBox<>();
        jLabel47 = new javax.swing.JLabel();
        txtBuscarOrdenSalida = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel45 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        myButton5 = new metodos.MyButton();
        txtBuscarDevolucion = new javax.swing.JTextField();
        jLabel48 = new javax.swing.JLabel();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 14)); // NOI18N

        myButton3.setForeground(new java.awt.Color(255, 255, 255));
        myButton3.setText("Agregar Orden");
        myButton3.setBorderColor(new java.awt.Color(19, 102, 217));
        myButton3.setColor(new java.awt.Color(19, 102, 217));
        myButton3.setColorClick(new java.awt.Color(19, 102, 217));
        myButton3.setColorOver(new java.awt.Color(66, 139, 225));
        myButton3.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 14)); // NOI18N
        myButton3.setRadius(10);
        myButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myButton3ActionPerformed(evt);
            }
        });

        tblOrdenesEntrada.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tblOrdenesEntrada.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Productos", "Valor del pedido", "Cantidad", "Orden ID", "Entrega esperada", "Estatus"
            }
        ));
        tblOrdenesEntrada.setEnabled(false);
        jScrollPane1.setViewportView(tblOrdenesEntrada);

        jLabel43.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 14)); // NOI18N
        jLabel43.setText("Seleccionar Sucursal:");

        cbSucursalOrdenes.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 12)); // NOI18N
        cbSucursalOrdenes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mostrar todas las sucursales" }));
        cbSucursalOrdenes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSucursalOrdenesActionPerformed(evt);
            }
        });

        jLabel46.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 14)); // NOI18N
        jLabel46.setText("Buscar orden por OrdenID:");

        txtBuscarOrden.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBuscarOrdenKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarOrdenKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBuscarOrdenKeyTyped(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 18)); // NOI18N
        jLabel1.setText("Ordenes de Entrada");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jScrollPane1))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel46)
                                    .addComponent(txtBuscarOrden, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 299, Short.MAX_VALUE)
                                .addComponent(jLabel43)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbSucursalOrdenes, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(180, 180, 180)
                                .addComponent(myButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(myButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbSucursalOrdenes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel43))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel46)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBuscarOrden, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 545, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Ordenes de entrada", jPanel3);

        jLabel22.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 18)); // NOI18N
        jLabel22.setText("Ordenes de Salida");

        jLabel23.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(1, 112, 239));
        jLabel23.setText("Ordenes Totales");

        jLabel24.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        jLabel24.setText("37");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22)
                    .addComponent(jLabel24)
                    .addComponent(jLabel23))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel22)
                .addGap(18, 18, 18)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel24)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jLabel41.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 18)); // NOI18N
        jLabel41.setText("Ordenes");

        myButton8.setForeground(new java.awt.Color(255, 255, 255));
        myButton8.setText("Agregar Orden");
        myButton8.setBorderColor(new java.awt.Color(19, 102, 217));
        myButton8.setColor(new java.awt.Color(19, 102, 217));
        myButton8.setColorClick(new java.awt.Color(19, 102, 217));
        myButton8.setColorOver(new java.awt.Color(66, 139, 225));
        myButton8.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 14)); // NOI18N
        myButton8.setRadius(10);
        myButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myButton8ActionPerformed(evt);
            }
        });

        tblOrdenesSalida.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        tblOrdenesSalida.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Productos", "Valor del pedido", "Cantidad", "Orden ID", "Entrega esperada", "Estatus"
            }
        ));
        tblOrdenesSalida.setEnabled(false);
        jScrollPane2.setViewportView(tblOrdenesSalida);

        jLabel44.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 14)); // NOI18N
        jLabel44.setText("Seleccionar Sucursal:");

        cbSucursalOrdenes1.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 12)); // NOI18N
        cbSucursalOrdenes1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mostrar todas las sucursales" }));
        cbSucursalOrdenes1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSucursalOrdenes1ActionPerformed(evt);
            }
        });

        jLabel47.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 14)); // NOI18N
        jLabel47.setText("Buscar orden por OrdenID:");

        txtBuscarOrdenSalida.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBuscarOrdenSalidaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarOrdenSalidaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBuscarOrdenSalidaKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel41)
                        .addGap(125, 125, 125)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel47)
                            .addComponent(txtBuscarOrdenSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 152, Short.MAX_VALUE)
                        .addComponent(jLabel44)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbSucursalOrdenes1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(133, 133, 133)
                        .addComponent(myButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jScrollPane2)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cbSucursalOrdenes1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel44)
                                .addComponent(myButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel47)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtBuscarOrdenSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel41)))
                .addGap(14, 14, 14)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 419, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Ordenes de salida", jPanel2);

        jPanel9.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        jPanel9.setMinimumSize(new java.awt.Dimension(1230, 720));

        jLabel45.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 18)); // NOI18N
        jLabel45.setText("Devoluciones");

        jTable1.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Devolución ID", "Motivo", "Producto ID", "Cantidad Devuelta", "Fecha de Devolución", "Proveedor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setEnabled(false);
        jScrollPane3.setViewportView(jTable1);

        myButton5.setForeground(new java.awt.Color(255, 255, 255));
        myButton5.setText("Registrar Devolución");
        myButton5.setBorderColor(new java.awt.Color(19, 102, 217));
        myButton5.setColor(new java.awt.Color(19, 102, 217));
        myButton5.setColorClick(new java.awt.Color(19, 102, 217));
        myButton5.setColorOver(new java.awt.Color(66, 139, 225));
        myButton5.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 14)); // NOI18N
        myButton5.setRadius(10);
        myButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myButton5ActionPerformed(evt);
            }
        });

        txtBuscarDevolucion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBuscarDevolucionKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarDevolucionKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBuscarDevolucionKeyTyped(evt);
            }
        });

        jLabel48.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 14)); // NOI18N
        jLabel48.setText("Buscar devolución por DevoluciónID:");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel45)
                        .addGap(286, 286, 286)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtBuscarDevolucion, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel48))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(myButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 1160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(247, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(myButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel48)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBuscarDevolucion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel45)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 562, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1426, Short.MAX_VALUE)
            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel8Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel8Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Devoluciones", jPanel8);

        jPanel1.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 1210, 710));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1244, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 760, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void myButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButton3ActionPerformed
        openFormPanel(1380, 680, "Agregar nueva orden de entrada");
    }//GEN-LAST:event_myButton3ActionPerformed

    private void myButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButton8ActionPerformed
        pnlAgregarOrdenSalida ordenesSalida = new  pnlAgregarOrdenSalida();

        JFrame formFrame = new JFrame("Agregar orden de salida");
        formFrame.setSize(1310, 618);
        formFrame.setLocationRelativeTo(p); 

        JPanel formPanel = new JPanel();

        formFrame.add(ordenesSalida.pnlOrdenSalida);
        formFrame.setVisible(true);
    }//GEN-LAST:event_myButton8ActionPerformed

    private void cbSucursalOrdenesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSucursalOrdenesActionPerformed
        try {
            co.LlenarTablaOrdenesEntrada(tblOrdenesEntrada, cbSucursalOrdenes.getSelectedIndex());
        } catch (SQLException ex) {
            Logger.getLogger(pnlInventario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cbSucursalOrdenesActionPerformed

    private void cbSucursalOrdenes1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSucursalOrdenes1ActionPerformed
        try {
            co.LlenarTablaOrdenesSalida(tblOrdenesSalida, cbSucursalOrdenes1.getSelectedIndex());
        } catch (SQLException ex) {
            Logger.getLogger(pnlOrdenes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cbSucursalOrdenes1ActionPerformed

    private void myButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButton5ActionPerformed
        pnlAgregrarDevolucion dev = new pnlAgregrarDevolucion();

        JFrame formFrame = new JFrame("Agregar devolución");
        formFrame.setSize(550, 620);
        formFrame.setLocationRelativeTo(p);

        JPanel formPanel = new JPanel();

        formFrame.add(dev.pnlDevoluciones);
        formFrame.setVisible(true);
    }//GEN-LAST:event_myButton5ActionPerformed

    private void txtBuscarOrdenKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarOrdenKeyPressed

    }//GEN-LAST:event_txtBuscarOrdenKeyPressed

    private void txtBuscarOrdenKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarOrdenKeyTyped

    }//GEN-LAST:event_txtBuscarOrdenKeyTyped

    private void txtBuscarOrdenKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarOrdenKeyReleased
        if(txtBuscarOrden.getText().isBlank()){
            try {
                co.LlenarTablaOrdenesEntrada(tblOrdenesEntrada, cbSucursalOrdenes.getSelectedIndex());
            } catch (SQLException ex) {
                Logger.getLogger(pnlOrdenes.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            try {
                co.BuscarOrdenEntrada(tblOrdenesEntrada, Integer.parseInt(txtBuscarOrden.getText()));
            } catch (SQLException ex) {
                Logger.getLogger(pnlOrdenes.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_txtBuscarOrdenKeyReleased

    private void txtBuscarOrdenSalidaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarOrdenSalidaKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarOrdenSalidaKeyPressed

    private void txtBuscarOrdenSalidaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarOrdenSalidaKeyReleased
                if(txtBuscarOrdenSalida.getText().isBlank()){
            try {
                co.LlenarTablaOrdenesSalida(tblOrdenesSalida, cbSucursalOrdenes1.getSelectedIndex());
            } catch (SQLException ex) {
                Logger.getLogger(pnlOrdenes.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            try {
                co.BuscarOrdenesSalida(tblOrdenesSalida, Integer.parseInt(txtBuscarOrdenSalida.getText()));
            } catch (SQLException ex) {
                Logger.getLogger(pnlOrdenes.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_txtBuscarOrdenSalidaKeyReleased

    private void txtBuscarOrdenSalidaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarOrdenSalidaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarOrdenSalidaKeyTyped

    private void txtBuscarDevolucionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarDevolucionKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarDevolucionKeyPressed

    private void txtBuscarDevolucionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarDevolucionKeyReleased
        if(txtBuscarDevolucion.getText().isBlank()){
            try {
                co.LlenarTablaDevolucionProductos(jTable1);
            } catch (SQLException ex) {
                Logger.getLogger(pnlOrdenes.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            try {
                co.BuscarDevolucionProductos(jTable1, Integer.parseInt(txtBuscarDevolucion.getText()));
            } catch (SQLException ex) {
                Logger.getLogger(pnlOrdenes.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_txtBuscarDevolucionKeyReleased

    private void txtBuscarDevolucionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarDevolucionKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarDevolucionKeyTyped

    private void autoResizeColumn(JTable jTable1) {
        JTableHeader header = jTable1.getTableHeader();
        int rowCount = jTable1.getRowCount();

        final Enumeration columns = jTable1.getColumnModel().getColumns();
        while (columns.hasMoreElements()) {
            TableColumn column = (TableColumn) columns.nextElement();
            int col = header.getColumnModel().getColumnIndex(column.getIdentifier());
            int width = (int) jTable1.getTableHeader().getDefaultRenderer()
                    .getTableCellRendererComponent(jTable1, column.getIdentifier(), false, false, -1, col).getPreferredSize().getWidth();

            for (int row = 0; row < rowCount; row++) {
                int preferedWidth = (int) jTable1.getCellRenderer(row, col).getTableCellRendererComponent(jTable1,
                        jTable1.getValueAt(row, col), false, false, row, col).getPreferredSize().getWidth();
                width = Math.max(width, preferedWidth);
            }
            header.setResizingColumn(column); // this line is very important
            column.setWidth(width + jTable1.getIntercellSpacing().width);
        }
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbSucursalOrdenes;
    private javax.swing.JComboBox<String> cbSucursalOrdenes1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private metodos.MyButton myButton3;
    private metodos.MyButton myButton5;
    private metodos.MyButton myButton8;
    private javax.swing.JTable tblOrdenesEntrada;
    private javax.swing.JTable tblOrdenesSalida;
    private javax.swing.JTextField txtBuscarDevolucion;
    private javax.swing.JTextField txtBuscarOrden;
    private javax.swing.JTextField txtBuscarOrdenSalida;
    // End of variables declaration//GEN-END:variables

        private void openFormPanel(int width, int height, String title) {
        pnlAgregarOrdenEntrada ordenesEntrada = new  pnlAgregarOrdenEntrada();
        // Lógica para abrir el panel tipo formulario aquí
        // Puedes crear un nuevo marco (JFrame) o un diálogo modal (JDialog) para mostrar el formulario.
        // Aquí solo crearé un JFrame simple como ejemplo:

        JFrame formFrame = new JFrame(title);
        formFrame.setSize(width, height);
        formFrame.setLocationRelativeTo(p); // Centra el formulario con respecto al marco principal

        JPanel formPanel = new JPanel();
        // Agrega aquí los elementos del formulario que desees

        formFrame.add(ordenesEntrada.pnlOrdenesEntrada);
        formFrame.setVisible(true);
    }
    
    class RoundedPanel extends JPanel {

        private Color backgroundColor;
        private int cornerRadius = 15;

        public RoundedPanel(LayoutManager layout, int radius) {
            super(layout);
            cornerRadius = radius;
        }

        public RoundedPanel(LayoutManager layout, int radius, Color bgColor) {
            super(layout);
            cornerRadius = radius;
            backgroundColor = bgColor;
        }

        public RoundedPanel(int radius) {
            super();
            cornerRadius = radius;

        }

        public RoundedPanel(int radius, Color bgColor) {
            super();
            cornerRadius = radius;
            backgroundColor = bgColor;
        }

        @Override
        protected void paintComponent(Graphics g) {
            super.paintComponent(g);
            Dimension arcs = new Dimension(cornerRadius, cornerRadius);
            int width = getWidth();
            int height = getHeight();
            Graphics2D graphics = (Graphics2D) g;
            graphics.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
            //Draws the rounded panel with borders.
            if (backgroundColor != null) {
                graphics.setColor(backgroundColor);
            } else {
                graphics.setColor(getBackground());
            }
            graphics.fillRoundRect(0, 0, width - 1, height - 1, arcs.width, arcs.height); //paint background
            graphics.setColor(getForeground());
//            graphics.drawRoundRect(0, 0, width-1, height-1, arcs.width, arcs.height); //paint border
//             
        }

    }
}
